version: "3.8"
services:
  web:
    build: ./booktracker
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./booktracker/:/usr/src/booktracker/
    ports:
      - 8000:8000
    environment:
      - .env
    depends_on:
      - db
    
  db:
    container_name: pg_container_bookcatalog
    image: postgres:14.1-alpine3.15
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
       - "5432:5432"
    volumes:
      - "${PWD}/data/initdb/:/docker-entrypoint-initdb.d/"